#ifdef PYMGOS
#include "Atom.h"

using namespace std;
using namespace V;

#include <pybind11/pybind11.h>
namespace py = pybind11;

void init_Atom(py::module &m) {
    py::class_<Atom>(m, "Atom")
        .def(py::init<>())
        .def(py::init<const Atom &>())

        .def("serial_number", &Atom::serial_number, "Gets the serial number of atom")
        .def("type", &Atom::type, "Gets the atom type")
        .def("geometry", &Atom::geometry, "Gets the atom geometry")
        .def("name", &Atom::name, "Gets the atom name")
        .def("residue_type", &Atom::residue_type, "Gets the type of a residue which contains the atom")
        .def("residue_sequence_number", &Atom::residue_sequence_number, "Gets the sequence number of a residue which contains the atom")
        .def("residue_name_3_letters", &Atom::residue_name_3_letters, "Gets the three-letter abbreviated name of a residue which contains the atom")
        .def("residue_name", &Atom::residue_name, "Gets the full name of a residue which contains the atom")
        .def("chain_ID", &Atom::chain_ID, "Gets the ID of chain which contains the atom")
        .def("is_in_hydrophobic_residue", &Atom::is_in_hydrophobic_residue, "Checks whether the atom is in a hydrophobic residue or not")
        .def("is_in_hydrophilic_residue", &Atom::is_in_hydrophilic_residue, "Checks whether the atom is in a hydrophilic residue or not")
        .def("is_in_polar_residue", &Atom::is_in_polar_residue, "Checks whether the atom is in a polar residue or not")
        .def("is_in_charged_residue", &Atom::is_in_charged_residue, "Checks whether the atom is in a charged residue or not")
        .def("is_in_positively_charged_residue", &Atom::is_in_positively_charged_residue, "Checks whether the atom is in a positively charged residue or not")
        .def("is_in_negatively_charged_residue", &Atom::is_in_negatively_charged_residue, "Checks whether the atom is in a negatively charged residue or not")
        .def("set_serial_number", &Atom::set_serial_number, "Sets the serial number of atom")
        .def("set_type", &Atom::set_type, "Sets the atom type")
        .def("set_geometry", &Atom::set_geometry, "Sets the atom geometry")
        .def("set_name", &Atom::set_name, "Sets the atom name.")
        .def("set_residue_type", &Atom::set_residue_type, "Sets the type of a residue which contains the atom")
        .def("set_residue_sequence_number", &Atom::set_residue_sequence_number, "Sets the sequence number of a residue which contains the atom")
        .def("set_chain_ID", &Atom::set_chain_ID, "Sets the ID of chain which contains the atom");

    py::enum_<AtomType>(m, "AtomType", py::arithmetic())
        .value("UNK_ATOM", AtomType::UNK_ATOM)
        .value("H_ATOM", AtomType::H_ATOM)
        .value("HE_ATOM", AtomType::HE_ATOM)
        .value("LI_ATOM", AtomType::LI_ATOM)
        .value("BE_ATOM", AtomType::BE_ATOM)
        .value("B_ATOM", AtomType::B_ATOM)
        .value("C_ATOM", AtomType::C_ATOM)
        .value("N_ATOM", AtomType::N_ATOM)
        .value("O_ATOM", AtomType::O_ATOM)
        .value("F_ATOM", AtomType::F_ATOM)
        .value("NE_ATOM", AtomType::NE_ATOM)
        .value("NA_ATOM", AtomType::NA_ATOM)
        .value("MG_ATOM", AtomType::MG_ATOM)
        .value("AL_ATOM", AtomType::AL_ATOM)
        .value("SI_ATOM", AtomType::SI_ATOM)
        .value("P_ATOM", AtomType::P_ATOM)
        .value("S_ATOM", AtomType::S_ATOM)
        .value("CL_ATOM", AtomType::CL_ATOM)
        .value("AR_ATOM", AtomType::AR_ATOM)
        .value("K_ATOM", AtomType::K_ATOM)
        .value("CA_ATOM", AtomType::CA_ATOM)
        .value("SC_ATOM", AtomType::SC_ATOM)
        .value("TI_ATOM", AtomType::TI_ATOM)
        .value("V_ATOM", AtomType::V_ATOM)
        .value("CR_ATOM", AtomType::CR_ATOM)
        .value("MN_ATOM", AtomType::MN_ATOM)
        .value("FE_ATOM", AtomType::FE_ATOM)
        .value("CO_ATOM", AtomType::CO_ATOM)
        .value("NI_ATOM", AtomType::NI_ATOM)
        .value("CU_ATOM", AtomType::CU_ATOM)
        .value("ZN_ATOM", AtomType::ZN_ATOM)
        .value("GA_ATOM", AtomType::GA_ATOM)
        .value("GE_ATOM", AtomType::GE_ATOM)
        .value("AS_ATOM", AtomType::AS_ATOM)
        .value("SE_ATOM", AtomType::SE_ATOM)
        .value("BR_ATOM", AtomType::BR_ATOM)
        .value("KR_ATOM", AtomType::KR_ATOM)
        .value("RB_ATOM", AtomType::RB_ATOM)
        .value("SR_ATOM", AtomType::SR_ATOM)
        .value("Y_ATOM", AtomType::Y_ATOM)
        .value("ZR_ATOM", AtomType::ZR_ATOM)
        .value("NB_ATOM", AtomType::NB_ATOM)
        .value("MO_ATOM", AtomType::MO_ATOM)
        .value("TC_ATOM", AtomType::TC_ATOM)
        .value("RU_ATOM", AtomType::RU_ATOM)
        .value("RH_ATOM", AtomType::RH_ATOM)
        .value("PD_ATOM", AtomType::PD_ATOM)
        .value("AG_ATOM", AtomType::AG_ATOM)
        .value("CD_ATOM", AtomType::CD_ATOM)
        .value("IN_ATOM", AtomType::IN_ATOM)
        .value("SN_ATOM", AtomType::SN_ATOM)
        .value("SB_ATOM", AtomType::SB_ATOM)
        .value("TE_ATOM", AtomType::TE_ATOM)
        .value("I_ATOM", AtomType::I_ATOM)
        .value("XE_ATOM", AtomType::XE_ATOM)
        .value("CS_ATOM", AtomType::CS_ATOM)
        .value("BA_ATOM", AtomType::BA_ATOM)
        .value("LA_ATOM", AtomType::LA_ATOM)
        .value("CE_ATOM", AtomType::CE_ATOM)
        .value("PR_ATOM", AtomType::PR_ATOM)
        .value("ND_ATOM", AtomType::ND_ATOM)
        .value("PM_ATOM", AtomType::PM_ATOM)
        .value("SM_ATOM", AtomType::SM_ATOM)
        .value("EU_ATOM", AtomType::EU_ATOM)
        .value("GD_ATOM", AtomType::GD_ATOM)
        .value("TB_ATOM", AtomType::TB_ATOM)
        .value("DY_ATOM", AtomType::DY_ATOM)
        .value("HO_ATOM", AtomType::HO_ATOM)
        .value("ER_ATOM", AtomType::ER_ATOM)
        .value("TM_ATOM", AtomType::TM_ATOM)
        .value("YB_ATOM", AtomType::YB_ATOM)
        .value("LU_ATOM", AtomType::LU_ATOM)
        .value("HF_ATOM", AtomType::HF_ATOM)
        .value("TA_ATOM", AtomType::TA_ATOM)
        .value("W_ATOM", AtomType::W_ATOM)
        .value("RE_ATOM", AtomType::RE_ATOM)
        .value("OS_ATOM", AtomType::OS_ATOM)
        .value("IR_ATOM", AtomType::IR_ATOM)
        .value("PT_ATOM", AtomType::PT_ATOM)
        .value("AU_ATOM", AtomType::AU_ATOM)
        .value("HG_ATOM", AtomType::HG_ATOM)
        .value("TL_ATOM", AtomType::TL_ATOM)
        .value("PB_ATOM", AtomType::PB_ATOM)
        .value("BI_ATOM", AtomType::BI_ATOM)
        .value("PO_ATOM", AtomType::PO_ATOM)
        .value("AT_ATOM", AtomType::AT_ATOM)
        .value("RN_ATOM", AtomType::RN_ATOM)
        .value("FR_ATOM", AtomType::FR_ATOM)
        .value("RA_ATOM", AtomType::RA_ATOM)
        .value("AC_ATOM", AtomType::AC_ATOM)
        .value("TH_ATOM", AtomType::TH_ATOM)
        .value("PA_ATOM", AtomType::PA_ATOM)
        .value("U_ATOM", AtomType::U_ATOM)
        .value("NP_ATOM", AtomType::NP_ATOM)
        .value("PU_ATOM", AtomType::PU_ATOM)
        .value("AM_ATOM", AtomType::AM_ATOM)
        .value("CM_ATOM", AtomType::CM_ATOM)
        .value("BK_ATOM", AtomType::BK_ATOM)
        .value("CF_ATOM", AtomType::CF_ATOM)
        .value("ES_ATOM", AtomType::ES_ATOM)
        .value("FM_ATOM", AtomType::FM_ATOM)
        .value("MD_ATOM", AtomType::MD_ATOM)
        .value("NO_ATOM", AtomType::NO_ATOM)
        .value("LR_ATOM", AtomType::LR_ATOM)
        .export_values();

    py::enum_<ResidueType>(m, "ResidueType", py::arithmetic())
        .value("UNK_RESIDUE",       ResidueType::UNK_RESIDUE      )
        .value("ALA_AMINO_RESIDUE", ResidueType::ALA_AMINO_RESIDUE)
        .value("ASX_AMINO_RESIDUE", ResidueType::ASX_AMINO_RESIDUE)
        .value("CYS_AMINO_RESIDUE", ResidueType::CYS_AMINO_RESIDUE)
        .value("CYH_AMINO_RESIDUE", ResidueType::CYH_AMINO_RESIDUE)
        .value("CSH_AMINO_RESIDUE", ResidueType::CSH_AMINO_RESIDUE)
        .value("CSS_AMINO_RESIDUE", ResidueType::CSS_AMINO_RESIDUE)
        .value("CYX_AMINO_RESIDUE", ResidueType::CYX_AMINO_RESIDUE)
        .value("ASP_AMINO_RESIDUE", ResidueType::ASP_AMINO_RESIDUE)
        .value("GLU_AMINO_RESIDUE", ResidueType::GLU_AMINO_RESIDUE)
        .value("PHE_AMINO_RESIDUE", ResidueType::PHE_AMINO_RESIDUE)
        .value("GLY_AMINO_RESIDUE", ResidueType::GLY_AMINO_RESIDUE)
        .value("HIS_AMINO_RESIDUE", ResidueType::HIS_AMINO_RESIDUE)
        .value("ILE_AMINO_RESIDUE", ResidueType::ILE_AMINO_RESIDUE)
        .value("ILU_AMINO_RESIDUE", ResidueType::ILU_AMINO_RESIDUE)
        .value("LYS_AMINO_RESIDUE", ResidueType::LYS_AMINO_RESIDUE)
        .value("LEU_AMINO_RESIDUE", ResidueType::LEU_AMINO_RESIDUE)
        .value("MET_AMINO_RESIDUE", ResidueType::MET_AMINO_RESIDUE)
        .value("ASN_AMINO_RESIDUE", ResidueType::ASN_AMINO_RESIDUE)
        .value("PRO_AMINO_RESIDUE", ResidueType::PRO_AMINO_RESIDUE)
        .value("PR0_AMINO_RESIDUE", ResidueType::PR0_AMINO_RESIDUE)
        .value("PRZ_AMINO_RESIDUE", ResidueType::PRZ_AMINO_RESIDUE)
        .value("GLN_AMINO_RESIDUE", ResidueType::GLN_AMINO_RESIDUE)
        .value("ARG_AMINO_RESIDUE", ResidueType::ARG_AMINO_RESIDUE)
        .value("SER_AMINO_RESIDUE", ResidueType::SER_AMINO_RESIDUE)
        .value("THR_AMINO_RESIDUE", ResidueType::THR_AMINO_RESIDUE)
        .value("VAL_AMINO_RESIDUE", ResidueType::VAL_AMINO_RESIDUE)
        .value("TRP_AMINO_RESIDUE", ResidueType::TRP_AMINO_RESIDUE)
        .value("TRY_AMINO_RESIDUE", ResidueType::TRY_AMINO_RESIDUE)
        .value("TYR_AMINO_RESIDUE", ResidueType::TYR_AMINO_RESIDUE)
        .value("GLX_AMINO_RESIDUE", ResidueType::GLX_AMINO_RESIDUE)
        .value("A_DNA_RESIDUE",     ResidueType::A_DNA_RESIDUE    )
        .value("AM_DNA_RESIDUE",    ResidueType::AM_DNA_RESIDUE   )
        .value("C_DNA_RESIDUE",     ResidueType::C_DNA_RESIDUE    )
        .value("CM_DNA_RESIDUE",    ResidueType::CM_DNA_RESIDUE   )
        .value("G_DNA_RESIDUE",     ResidueType::G_DNA_RESIDUE    )
        .value("GM_DNA_RESIDUE",    ResidueType::GM_DNA_RESIDUE   )
        .value("I_DNA_RESIDUE",     ResidueType::I_DNA_RESIDUE    )
        .value("IM_DNA_RESIDUE",    ResidueType::IM_DNA_RESIDUE   )
        .value("T_DNA_RESIDUE",     ResidueType::T_DNA_RESIDUE    )
        .value("TM_DNA_RESIDUE",    ResidueType::TM_DNA_RESIDUE   )
        .value("A_RNA_RESIDUE",     ResidueType::A_RNA_RESIDUE    )
        .value("AM_RNA_RESIDUE",    ResidueType::AM_RNA_RESIDUE   )
        .value("C_RNA_RESIDUE",     ResidueType::C_RNA_RESIDUE    )
        .value("CM_RNA_RESIDUE",    ResidueType::CM_RNA_RESIDUE   )
        .value("G_RNA_RESIDUE",     ResidueType::G_RNA_RESIDUE    )
        .value("GM_RNA_RESIDUE",    ResidueType::GM_RNA_RESIDUE   )
        .value("I_RNA_RESIDUE",     ResidueType::I_RNA_RESIDUE    )
        .value("IM_RNA_RESIDUE",    ResidueType::IM_RNA_RESIDUE   )
        .value("U_RNA_RESIDUE",     ResidueType::U_RNA_RESIDUE    )
        .value("UM_RNA_RESIDUE",    ResidueType::UM_RNA_RESIDUE   )
        .value("HOH_RESIDUE",       ResidueType::HOH_RESIDUE      )
        .export_values(); 
}
#endif